"""Regenerate the test fixtures using the REFERENCE implementation.

Python, and not nbb, for the reason `org-apache-parquet` gives: the only
trustworthy oracle for an Avro decoder is a file written by Avro's own writer.
A fixture this repo generated itself would test the decoder against its own
misunderstanding of the format -- and Avro is the format where that matters
most, because it writes NO TYPE TAGS. The bytes of a long and the bytes of a
string length are the same varint, so a decoder that is wrong about the schema
produces plausible values rather than an error.

    python3 -m venv .venv && .venv/bin/pip install fastavro
    .venv/bin/python test/fixtures/generate.py
"""
import fastavro
import pathlib

here = pathlib.Path(__file__).parent

SCHEMA = {
    "type": "record",
    "name": "Sale",
    "fields": [
        {"name": "price", "type": "long"},
        {"name": "region", "type": "string"},
        # The nullable union that most real Avro data is made of.
        {"name": "note", "type": ["null", "string"]},
        {"name": "ratio", "type": "double"},
        {"name": "ok", "type": "boolean"},
    ],
}

# Separate, because Avro decodes a RECORD AT A TIME. A field past 2^53 makes
# the whole record undecodable on ClojureScript, not just that field -- unlike
# Parquet and Arrow, where columns are read independently and only the
# offending one refuses. Keeping it in the main table would make every value
# assertion unrunnable on cljs rather than just this one.
BIG_SCHEMA = {
    "type": "record",
    "name": "Big",
    "fields": [{"name": "big", "type": "long"}],
}
BIG_ROWS = [{"big": 4611686018427387905}, {"big": -4611686018427387905},
            {"big": 0}]

ROWS = [
    {"price": 10, "region": "east", "note": None, "ratio": 1.5, "ok": True},
    {"price": 20, "region": "east", "note": "clearance", "ratio": 2.25, "ok": False},
    {"price": 30, "region": "west", "note": None, "ratio": -0.5, "ok": True},
]


def write(name, codec="null", sync_interval=None, schema=None, rows=None):
    kw = {"codec": codec}
    if sync_interval is not None:
        kw["sync_interval"] = sync_interval
    with open(here / name, "wb") as f:
        fastavro.writer(f, schema or SCHEMA, rows if rows is not None else ROWS, **kw)


# plain.avro — uncompressed, the subset this reader decodes without a codec.
write("plain.avro")

# deflate.avro — Avro's `deflate` is RAW deflate with no gzip header, which is
# why this goes through inflate-raw rather than gunzip. Getting that wrong
# fails on the first byte, loudly, which is the good case.
write("deflate.avro", codec="deflate")

# zstd.avro — the `zstandard` codec, through the same decoder the Parquet and
# Arrow readers use.
write("zstd.avro", codec="zstandard")

# multi-block.avro — a tiny sync interval forces several blocks, so the block
# walk and the sync-marker check are exercised rather than assumed. A
# single-block file cannot tell a correct walk from one that never moved.
write("multi-block.avro", sync_interval=1)

# snappy.avro — OUTSIDE the supported set, and it has to stay that way. Avro
# frames snappy with a 4-byte big-endian CRC-32C suffix, so the raw-block
# snappy decoder elsewhere in this workspace would decode most blocks and
# corrupt the checksum on all of them. This fixture is the witness that the
# RECORD COUNT is still readable from a file whose blocks cannot be undone.
write("snappy.avro", codec="snappy")

# big-ints.avro -- see BIG_SCHEMA. Exact on the JVM, refused on ClojureScript.
write("big-ints.avro", schema=BIG_SCHEMA, rows=BIG_ROWS)


def edn(x):
    if x is None:
        return "nil"
    if x is True:
        return "true"
    if x is False:
        return "false"
    if isinstance(x, str):
        return '"' + x.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(x, float):
        return repr(x)
    if isinstance(x, int):
        return str(x)
    if isinstance(x, list):
        return "[" + " ".join(edn(v) for v in x) + "]"
    if isinstance(x, dict):
        return "{" + " ".join(f'"{k}" {edn(v)}' for k, v in x.items()) + "}"
    raise TypeError(type(x))


# ground-truth.edn — emitted by the same script from the files it just wrote,
# so a regenerated fixture cannot drift from the assertions about it.
(here / "ground-truth.edn").write_text(
    ";; GENERATED by generate.py from the fastavro reference writer. Do not edit.\n"
    "{\n"
    '  "fields" ' + edn([f["name"] for f in SCHEMA["fields"]]) + "\n"
    '  "rows" ' + edn(ROWS) + "\n"
    '  "big" ' + edn([r["big"] for r in BIG_ROWS]) + "\n"
    "}\n"
)

for p in sorted(here.glob("*.avro")):
    print(p.name, p.stat().st_size, "bytes")
print("fastavro", fastavro.__version__)
